### ISSUE TITLE
Best way to save and load model for inference

### ISSUE THREAD

**Issue by advaitb** [slimgroup/WISE.jl#4]
What is the best way to save and load summarized net/ or conditional glow model? I've seen [put_params](https://github.com/slimgroup/Software.SEG2021/issues/1) being used but it only seems to have spport fore conditional hint. I'm trying to use the BSON module but is this the right way?

**Comment by ziyiyin97** [comment]
It involves reinitialization of the network, load the saved parameters, and then set them to be the network parameters.

``` julia

net_path = "/your/path"
unet_lev = BSON.load(net_path)["unet_lev"];
n_hidden = BSON.load(net_path)["n_hidden"];
L = BSON.load(net_path)["L"];
K = BSON.load(net_path)["K"];

unet = Unet(chan_obs,1,unet_lev);
trainmode!(unet, true);
unet = FluxBlock(Chain(unet)) |> device;

cond_net = NetworkConditionalGlow(1, 1, n_hidden,  L, K;  freeze_conv=true, split_scales=true, activation=SigmoidLayer(low=0.5f0,high=1.0f0)) |> device;
G        = SummarizedNet(cond_net, unet)

Params = BSON.load(net_path)["Params"]; 
noise_lev_x = BSON.load(net_path)["noise_lev_x"]; 
set_params!(G,Params)

# Load in unet summary net
G.sum_net.model = BSON.load(net_path)["unet_model"]; 
G = G |> device;
```

**Comment by advaitb** [comment]
@ziyiyin97 could you please elaborate what exactly are you loading here `G.sum_net.model = BSON.load(net_path)["unet_model"]; ` i.e what did you save?

**Comment by ziyiyin97** [comment]
Here documents what I saved https://github.com/slimgroup/WISE.jl/blob/f4185b5324248f58eaf9e8bf083148f2f3f3dde0/scripts/train_compass.jl#L399

**Comment by advaitb** [comment]
Thanks @ziyiyin97, I was able to successful carry out training and inference. Just as a follow-up, how many samples did you use for training and test for the OpenFWI dataset?

**Comment by ziyiyin97** [comment]
3000 velocity models in OpenFWI dataset are split into 2800 training, 150 validation, and 50 test samples. More information can be found in section 3 of https://arxiv.org/pdf/2401.06230.pdf

**Comment by advaitb** [comment]
Gotcha, thanks, closing this issue for now.
