### ISSUE TITLE
Fine tuning WISE results

### ISSUE THREAD

**Issue by advaitb** [slimgroup/WISE.jl#5]
Hi Francis,

Is any code to refine WISE results to get better posterior samples available? I wanted to test the generalizability of the results across multiple datasets. Thanks!

Regards,
Advait

**Comment by ziyiyin97** [comment]
Hi Advait,

Thanks for your interest. We are still in the process of finalizing the manuscript and the software release at this moment. I will ping you here once I make any progress.

Thanks,

Francis

**Comment by advaitb** [comment]
Awesome, thanks!

**Comment by ziyiyin97** [comment]
We just pushed out the preprint on ResearchGate http://dx.doi.org/10.13140/RG.2.2.34906.15044

I will find some time this week to push out the code. Will keep you posted @advaitb

**Comment by advaitb** [comment]
Thanks @ziyiyin97, excited to read!

**Comment by ziyiyin97** [comment]
Hi, we pushed out the code at https://github.com/slimgroup/WISER.jl @advaitb Look forward to your thoughts and let us know if any questions!
