### ISSUE TITLE
Replicating COMPASS results

### ISSUE THREAD

**Issue by advaitb** [slimgroup/WISE.jl#6]
Hi @ziyiyin97,

I'm running into some issues with replicating the COMPASS results with a 1d gradient background. I'm getting very fuzzy posterior samples around the salt/seabed region as shown below. Any ideas on how to fix this or what's going wrong? I've trained it on 400 slices.

![image](https://github.com/slimgroup/WISE.jl/assets/13657575/3cadae8a-e7c0-485f-9e8e-644a9ba31a65)

**Comment by ziyiyin97** [comment]
When you say `1d gradient` background, do you mean a velocity that monotonously increases along time? If that's the case, then your result would be worse. In the WISE paper, we used a `1d average` of the compass dataset, which is a better background model so it produces better posterior samples.

On a side note: sorry for the delay, I am swamped by a few other things at this moment. I will try to push out the WISER code in a few days. Thanks in advance for your understanding.

**Comment by advaitb** [comment]
Interesting, maybe I'm getting this wrong but I used the 1d gradient and it looks closer to what you used in the paper in 2(b) ? If I use the 1d average I get a smoothed original image? Does this look correct to you?

Gradient: ![image](https://github.com/slimgroup/WISE.jl/assets/13657575/58370cb8-3999-4e80-9311-a680f7172b71)
Average: ![image](https://github.com/slimgroup/WISE.jl/assets/13657575/ee1a5bce-e619-483a-aad7-fe668b9cec6c)

**Comment by ziyiyin97** [comment]
1D gradient is indeed challenging because the travel time might be extremely off. I used all 1040 samples to compute the average and then smoothed it as indicated in my code. I suspect you use fewer samples? I don't expect structures in the averaged velocity model.

**Comment by advaitb** [comment]
Thanks, that worked and I was able to approximately replicate results from the paper!
